import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F3F4',
    },
    backButton: {
        padding: 5,
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#000000',
        marginLeft: 15,
    },
    content: {
        flex: 1,
        paddingHorizontal: 30,
        paddingTop: 50,
        alignItems: 'center',
    },
    welcomeText: {
        fontSize: 18,
        color: '#7F8C8D',
        textAlign: 'center',
        lineHeight: 28,
        marginBottom: 40,
    },
    mainButton: {
        backgroundColor: '#3498DB',
        width: '100%',
        height: 55,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#3498DB',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 3,
    },
    buttonText: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '700',
    },
    // Form Styles
    formContent: {
        flex: 1,
        paddingTop: 20,
    },
    inputGroup: {
        marginBottom: 25,
    },
    labelRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    label: {
        fontSize: 18,
        fontWeight: '600',
        color: '#000000',
    },
    required: {
        color: '#E74C3C',
        marginLeft: 5,
        fontSize: 18,
    },
    input: {
        fontSize: 18,
        color: '#2C3E50',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F3F4',
    },
    textarea: {
        minHeight: 80,
        textAlignVertical: 'top',
    },
    checkboxContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginTop: 10,
        paddingHorizontal: 20,
    },
    checkbox: {
        width: 22,
        height: 22,
        borderWidth: 2,
        borderColor: '#BDC3C7',
        borderRadius: 4,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
        marginTop: 2,
    },
    checkboxChecked: {
        backgroundColor: '#3498DB',
        borderColor: '#3498DB',
    },
    checkboxText: {
        fontSize: 15,
        color: '#2C3E50',
        flex: 1,
        lineHeight: 22,
    },
    linkText: {
        color: '#3498DB',
        textDecorationLine: 'underline',
    },
    noteContainer: {
        paddingHorizontal: 20,
        marginTop: 20,
    },
    noteText: {
        fontSize: 12,
        color: '#95A5A6',
        lineHeight: 18,
        marginBottom: 5,
    },
    formFooter: {
        flexDirection: 'row',
        padding: 20,
        gap: 15,
    },
    cancelButton: {
        flex: 1,
        height: 50,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#3498DB',
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelButtonText: {
        color: '#3498DB',
        fontSize: 18,
        fontWeight: '600',
    },
    confirmButton: {
        flex: 1.2,
        height: 50,
        borderRadius: 12,
        backgroundColor: '#3498DB',
        alignItems: 'center',
        justifyContent: 'center',
    },
    confirmButtonText: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '600',
    },
    // Success Screen
    successCard: {
        width: '90%',
        backgroundColor: '#FFFFFF',
        borderRadius: 15,
        padding: 40,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 5,
        marginTop: 20,
        marginBottom: 30,
    },
    successIconContainer: {
        width: 80,
        height: 80,
        borderRadius: 40,
        borderWidth: 3,
        borderColor: '#2ECC71',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    successText: {
        fontSize: 22,
        fontWeight: '700',
        color: '#000000',
    },
});
